/**
 * @file firmware_storage.c
 * @brief ORB DRIVE OTA module firmware storage manager.
 */

#include "firmware_storage.h"

#include <stddef.h>
#include <stdint.h>

#include "esp_log.h"

static const char *TAG = "FW_STORAGE";

/*
 * Node firmware is embedded by ESP-IDF through EMBED_FILES
 * in main/CMakeLists.txt.
 *
 * The symbols are generated by the ESP-IDF build system.
 */
extern const uint8_t _binary_orbdrive_firmware_bin_start[];
extern const uint8_t _binary_orbdrive_firmware_bin_end[];

static bool s_initialized = false;

bool firmware_storage_init(void)
{
    if (s_initialized)
    {
        return true;
    }

    s_initialized = true;

    ESP_LOGI(
        TAG,
        "Firmware storage initialized"
    );

    return true;
}

bool firmware_storage_available(void)
{
    if (!s_initialized)
    {
        ESP_LOGE(
            TAG,
            "Firmware storage not initialized"
        );

        return false;
    }

    const size_t firmware_size =
        (size_t)(
            _binary_orbdrive_firmware_bin_end -
            _binary_orbdrive_firmware_bin_start
        );

    if (firmware_size == 0U)
    {
        ESP_LOGE(
            TAG,
            "Node firmware image is empty"
        );

        return false;
    }

    return true;
}

bool firmware_storage_get_image(
    firmware_image_t *image)
{
    if (image == NULL)
    {
        ESP_LOGE(
            TAG,
            "Invalid firmware image descriptor"
        );

        return false;
    }

    image->data = NULL;
    image->size = 0U;

    if (!s_initialized)
    {
        ESP_LOGE(
            TAG,
            "Firmware storage not initialized"
        );

        return false;
    }

    const size_t firmware_size =
        (size_t)(
            _binary_orbdrive_firmware_bin_end -
            _binary_orbdrive_firmware_bin_start
        );

    if (firmware_size == 0U)
    {
        ESP_LOGE(
            TAG,
            "Node firmware image is empty"
        );

        return false;
    }

    image->data =
        _binary_orbdrive_firmware_bin_start;

    image->size =
        firmware_size;

    ESP_LOGI(
        TAG,
        "Node firmware image ready: %u bytes",
        (unsigned int)firmware_size
    );

    return true;
}

void firmware_storage_release(
    firmware_image_t *image)
{
    if (image == NULL)
    {
        return;
    }

    /*
     * The image is embedded in the application image.
     * No dynamic memory was allocated by this module.
     */
    image->data = NULL;
    image->size = 0U;
}